### ISSUE TITLE
Cannot edit subcircuit appearance

### ISSUE THREAD

**Issue by wildptr** [lawrancej/logisim#109]
When the button "Edit viewed circuit's subcircuit appearance" button on the toolbar is clicked, a NullPointerException is thrown:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.cburch.draw.canvas.Canvas.setModel(Canvas.java:71)
	at com.cburch.logisim.gui.appear.AppearanceCanvas.setModel(AppearanceCanvas.java:113)
	at com.cburch.logisim.gui.appear.AppearanceCanvas.setCircuit(AppearanceCanvas.java:123)
	at com.cburch.logisim.gui.appear.AppearanceView.setCircuit(AppearanceView.java:80)
(and more)

**Comment by eric8he** [comment]
Yep. I have the same issue

**Comment by thewithz** [comment]
Also having this issue. 
EDIT: full stack trace
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.cburch.draw.canvas.Canvas.setModel(Canvas.java:71)
        at com.cburch.logisim.gui.appear.AppearanceCanvas.setModel(AppearanceCanvas.java:113)
        at com.cburch.logisim.gui.appear.AppearanceCanvas.setCircuit(AppearanceCanvas.java:123)
        at com.cburch.logisim.gui.appear.AppearanceView.setCircuit(AppearanceView.java:80)
        at com.cburch.logisim.gui.main.Frame.setEditorView(Frame.java:397)
        at com.cburch.logisim.gui.menu.Popups$CircuitPopup.actionPerformed(Popups.java:141)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2237)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2295)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
        at java.awt.Container.dispatchEventImpl(Container.java:2281)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThra:93)av
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`
