### ISSUE TITLE
Can't run .jar outside of gradlew run

### ISSUE THREAD

**Issue by JesseTG** [lawrancej/logisim#84]
When I try, I'm given this error:

```
jesse@jtg-ubuntu:~/Code/Source/logisim/build/libs$ java -jar ./*.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.cburch.logisim.LogisimVersion.<clinit>(LogisimVersion.java:16)
	at com.cburch.logisim.Main.<clinit>(Main.java:35)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
jesse@jtg-ubuntu:~/Code/Source/logisim/build/libs$ 
```

**Comment by mikespallino** [comment]
This is because we don't currently pack the libraries into the jar file. I will start working on fixing this.

**Comment by JesseTG** [comment]
Isn't it supposed to be just a few lines in Gradle?

**Comment by mikespallino** [comment]
Yeah, I was in class though. I just pushed the fix to my repository.

**Comment by JesseTG** [comment]
Awesome, thanks!  I'll leave this open until it's merged into upstream.

**Comment by lawrancej** [comment]
Thanks for the fix, too! :+1:
