### ISSUE TITLE
jar won't start

### ISSUE THREAD

**Issue by kloro2006** [lawrancej/logisim#89]
~/$ java -jar logisim-evolution-2.13.9.jar 
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: com.cburch.logisim.Main. Program will exit.
~/$

**Comment by mikespallino** [comment]
Are you sure you're trying to run this repository's jar? Our jar is called `logisim-2.7.2.jar` and is found under `/build/libs/`. If you can't find that run `gradlew build`. Hope this helps!

**Comment by AL3XEY** [comment]
You are right, it seems that kloro2006 is running [this repository](https://github.com/reds-heig/logisim-evolution)'s jar.

**Comment by kloro2006** [comment]
is logisim-2.7.2.jar better than logisim-generic-2.7.1.jar?




On 4/7/15, Alexandre Faucher <notifications@github.com> wrote:
> You are right, it seems that kloro2006 is running [this
> repository](https://github.com/reds-heig/logisim-evolution)'s jar.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/lawrancej/logisim/issues/89#issuecomment-90499760

**Comment by kloro2006** [comment]
i'm  trying to run logisim-evolution too. where can i post my problem about it?

**Comment by AL3XEY** [comment]
You can create an issue [here](https://github.com/reds-heig/logisim-evolution/issues) so that the developers of logisim-evolution can help you.
